config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  get "users/new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"

  # ユーザ管理機能
  get "/signup", to: "users#new"
  get "/users", to: "users#index"

  # ログイン機能
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # localhost:3000/posts
  resources :posts, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]

  # localhost:3000/users
  resources :users, only: [ :show, :new, :create, :edit, :update, :destroy ]

  # localhost:3000/account_activations
  resources :account_activations, only: [ :edit ]
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { minimum: 1, maximum: 50 }
    validates :content, presence: true, length: { minimum: 1, maximum: 1000 }
    validates :user_id, { presence: true }
    belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :logged_in_user, only: [ :new, :create, :edit, :update, :destroy ]
    before_action :ensure_correct_user, only: [ :edit, :update, :destroy ]

    def index
        @posts = Post.paginate(page: params[:page], per_page: 10)
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path, notice: "投稿に成功しました"
        else
            Rails.logger.info @post.errors.full_messages
            flash.now[:alert] = "投稿に失敗しました"
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path, notice: "更新に成功しました"
        else
            Rails.logger.info @post.errors.full_messages
            flash.now[:alert] = "更新に失敗しました"
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy!
        redirect_to posts_path, status: :see_other, notice: "削除に成功しました"
    end

    private

    def post_params
        params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
    end

    def ensure_correct_user
        @post = Post.find(params[:id])
        if @post.user_id != current_user.id && !current_user.admin?
            redirect_to posts_path, alert: "権限がありません"
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_with model: @post, class: "form-container" do |form| %>
    <div class="form-input">
        <%= form.label :title %> <%= form.text_field :title %>
    </div>

    <div class="form-input">
        <%= form.label :content %> <%= form.text_area :content %>
    </div>

    <div class="button-container">
        <%= form.submit "更新" %>
    </div>
<% end %>

app/views/posts/index.html.erb
<h1>Ruby on Rails 掲示板</h1>

<div class="button-container">
    <%= link_to "新しい投稿", new_post_path, class: "link-button" %>
</div>

<% if @posts.present? %>
    <div class="post-container">
        <%= will_paginate %>
        <ul>
            <% @posts.each do |post| %>
            <li>
                <div class="post-user-info">
                    <%= gravatar_for post.user %>
                    <%= link_to post.user.name, user_path(post.user) %>
                </div>
                <h2><%= post.title %></h2>
                <p><%= post.content %></p>
                <span><%= post.created_at %></span>
                <div class="button-container">
                    <%= link_to "編集", edit_post_path(post), class: "edit-button" %>
                    <%= link_to "削除", post,  data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: "delete-button" %>
                </div>
            </li>
            <% end %>
        </ul>
        <%= will_paginate %>
    </div>
<% else %>
    <p>投稿がありません</p>
<% end %>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>

<%= render 'shared/error_messages', object: @post %>

<%= form_with model: @post, class: "form-container" do |form| %>
    <div class="form-input">
        <%= form.label :title %> <%= form.text_field :title, class: 'form-control'%>
    </div>

    <div class="form-input">
        <%= form.label :content %> <%= form.text_area :content, class: 'form-control' %>
    </div>

    <div class="button-container">
        <%= form.submit "投稿" %>
    </div>
<% end %>